In [17]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.special import expit

In [3]:
K = 120
r1 = np.array([3, 5, 2, 7, 7, 2, 5, 3, 5, 11, 6, 6, 11, 4, 4, 2, 8, 8, 6,  
               5, 15, 4, 9, 9, 4, 12, 8, 8, 6, 8, 12, 4, 7, 16, 12, 9, 4, 7, 
               8, 11, 5, 12, 8, 17, 9, 3, 2, 7, 6, 5, 11, 14, 13, 8, 6, 4, 8, 
               4, 8, 7, 15, 15, 9, 9, 5, 6, 3, 9, 12, 14, 16, 17, 8, 8, 9, 5, 
               9, 11, 6, 14, 21, 16, 6, 9, 8, 9, 8, 4, 11, 11, 6, 9, 4, 4, 9, 
               9, 10, 14, 6, 3, 4, 6, 10, 4, 3, 3, 10, 4, 10, 5, 4, 3, 13, 1, 
               7, 5, 7, 6, 3, 7])
n1 = np.array([28, 21, 32, 35, 35, 38, 30, 43, 49, 53, 31, 35, 46, 53, 61, 
               40, 29, 44, 52, 55, 61, 31, 48, 44, 42, 53, 56, 71, 43, 43, 43, 
               40, 44, 70, 75, 71, 37, 31, 42, 46, 47, 55, 63, 91, 43, 39, 35, 
               32, 53, 49, 75, 64, 69, 64, 49, 29, 40, 27, 48, 43, 61, 77, 55, 
               60, 46, 28, 33, 32, 46, 57, 56, 78, 58, 52, 31, 28, 46, 42, 45, 
               63, 71, 69, 43, 50, 31, 34, 54, 46, 58, 62, 52, 41, 34, 52, 63, 
               59, 88, 62, 47, 53, 57, 74, 68, 61, 45, 45, 62, 73, 53, 39, 45, 
               51, 55, 41, 53, 51, 42, 46, 54, 32])
r0 = np.array([0, 2, 2, 1, 2, 0, 1, 1, 1, 2, 4, 4, 2, 1, 7, 4, 3, 5, 3, 2, 
               4, 1, 4, 5, 2, 7, 5, 8, 2, 3, 5, 4, 1, 6, 5, 11, 5, 2, 5, 8, 
               5, 6, 6, 10, 7, 5, 5, 2, 8, 1, 13, 9, 11, 9, 4, 4, 8, 6, 8, 6, 
               8, 14, 6, 5, 5, 2, 4, 2, 9, 5, 6, 7, 5, 10, 3, 2, 1, 7, 9, 13, 
               9, 11, 4, 8, 2, 3, 7, 4, 7, 5, 6, 6, 5, 6, 9, 7, 7, 7, 4, 2, 
               3, 4, 10, 3, 4, 2, 10, 5, 4, 5, 4, 6, 5, 3, 2, 2, 4, 6, 4, 1])
n0 = np.array([28, 21, 32, 35, 35, 38, 30, 43, 49, 53, 31, 35, 46, 53, 61, 
               40, 29, 44, 52, 55, 61, 31, 48, 44, 42, 53, 56, 71, 43, 43, 43, 
               40, 44, 70, 75, 71, 37, 31, 42, 46, 47, 55, 63, 91, 43, 39, 35, 
               32, 53, 49, 75, 64, 69, 64, 49, 29, 40, 27, 48, 43, 61, 77, 55, 
               60, 46, 28, 33, 32, 46, 57, 56, 78, 58, 52, 31, 28, 46, 42, 45, 
               63, 71, 69, 43, 50, 31, 34, 54, 46, 58, 62, 52, 41, 34, 52, 63, 
               59, 88, 62, 47, 53, 57, 74, 68, 61, 45, 45, 62, 73, 53, 39, 45, 
               51, 55, 41, 53, 51, 42, 46, 54, 32])
year = np.array([-10, -9, -9, -8, -8, -8, -7, -7, -7, -7, -6, -6, -6, -6, -6, 
                 -5, -5, -5, -5, -5, -5, -4, -4, -4, -4, -4, -4, -4, -3, -3, -3, 
                 -3, -3, -3, -3, -3, -2, -2, -2, -2, -2, -2, -2, -2, -2, -1, -1, 
                 -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
                 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 
                 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 
                 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 9, 9, 10])

In [4]:
[len(r1) == K, len(n1) == K, len(r0) == K, len(n0) == K, len(year) == K]

[True, True, True, True, True]

In [5]:
init_alpha = 0
init_beta1 = 0
init_beta2 = 0
init_sigma = 1
init_mu = np.zeros(120)
init_b  = np.zeros(120)

In [56]:
def Sampler(nchain, init_alpha, init_beta1, init_beta2, init_sigma, init_mu, init_b, prop_sd, K, r1, n1, r0, n0, year):
    
    chain = np.empty((nchain+1, 6), dtype = object)
    chain[0,0] = init_alpha
    chain[0,1] = init_beta1
    chain[0,2] = init_beta2
    chain[0,3] = init_mu
    chain[0,4] = init_b
    chain[0,5] = init_sigma
    
    alpha = init_alpha
    beta1 = init_beta1
    beta2 = init_beta2
    mu = init_mu
    b = init_b
    sigma = init_sigma
    
    log_psi = alpha + beta1 * year + beta2 * (year**2 - 22) + b
    p0 = expit(mu)
    p1 = expit(mu + log_psi)
    
    
    for i in range(nchain):
        
        # Mise à jour de alpha
        prop = np.random.normal(alpha, prop_sd[0])
        prop_log_psi = prop + beta1 * year + beta2 * (year**2 - 22) + b
        prop_p1 = expit(mu + prop_log_psi)
        
        top = - (prop**2 / (2 * 1e6)) + sum(r1 * np.log(prop_p1)) + sum((n1 - r1) * np.log(1 - prop_p1))
        bottom = - (alpha**2 / (2 * 1e6)) + sum(r1 * np.log(p1)) + sum((n1 - r1) * np.log(1 - p1))
        
        acc_prob = np.exp(top - bottom)
        
        print('hehe_alpha')
        
        if np.random.uniform() < acc_prob:
            alpha = prop
            log_psi = prop_log_psi
            p1 = prop_p1
        
        # Mise à jour de beta1
        prop = np.random.normal(beta1, prop_sd[1])
        prop_log_psi = alpha + prop * year + beta2 * (year**2 - 22) + b
        prop_p1 = expit(mu + prop_log_psi)
        
        top = - (prop**2 / (2 * 1e6)) + sum(r1 * np.log(prop_p1)) + sum((n1 - r1) * np.log(1 - prop_p1))
        bottom = - (beta1**2 / (2 * 1e6)) + sum(r1 * np.log(p1)) + sum((n1 - r1) * np.log(1 - p1))
        
        acc_prob = np.exp(top - bottom)
        
        print('hehe_beta1')
        if np.random.uniform() < acc_prob:
            beta1 = prop
            log_psi = prop_log_psi
            p1 = prop_p1
            
        # Mise à jour de beta2
        prop = np.random.normal(beta2, prop_sd[2])
        prop_log_psi = alpha + beta1 * year + prop * (year**2 - 22) + b
        prop_p1 = expit(mu + prop_log_psi)
        
        top = - (prop**2 / (2 * 1e6)) + sum(r1 * np.log(prop_p1)) + sum((n1 - r1) * np.log(1 - prop_p1))
        bottom = - (beta2**2 / (2 * 1e6)) + sum(r1 * np.log(p1)) + sum((n1 - r1) * np.log(1 - p1))
        
        acc_prob = np.exp(top - bottom)
        
        print('hehe_beta2')
        if np.random.uniform() < acc_prob:
            beta2 = prop
            log_psi = prop_log_psi
            p1 = prop_p1
            
        for j in range(K):
            # Mise à jour de mu
            ## même prop_sd pour tous?
            ##générer tout le vecteur à la fois o générer chaque mu_j séparément
            prop = np.random.normal(mu[j], prop_sd[3])
            prop_p0_j = expit(prop) 
            
            top = - (prop**2 / (2 * 1e6)) + r0[j] * np.log(prop_p0_j) + (n0[j] - r0[j]) * np.log(1 - prop_p0_j)
            bottom = - (mu[j]**2 / (2 * 1e6)) + r0[j] * np.log(p0[j]) + (n0[j] - r0[j]) * np.log(1 - p0[j])
            
            acc_prob = np.exp(top - bottom)
            if np.random.uniform() < acc_prob:
                mu[j] = prop
                p0[j] = prop_p0_j
                
            # Mise à jour de b
            prop = np.random.normal(b[j], prop_sd[4])
            prop_p1_j = expit(prop + log_psi[j])
            
            top = - (prop**2 / (2 * sigma)) + r1[j] * np.log(prop_p1_j) + (n1[j] - r1[j]) * np.log(1 - prop_p1_j)
            bottom = - (b[j]**2 / (2 * sigma)) + r1[j] * np.log(p1[j]) + (n1[j] - r1[j]) * np.log(1 - p1[j])
            
            acc_prob = np.exp(top - bottom)
            print("b")
            if np.random.uniform() < acc_prob:
                b[j] = prop
                p1[j] = prop_p1_j
            
    return(chain)
        
        
    
    

In [57]:
lol = Sampler(10, 2, 2, 2, 2, 2*np.ones(len(year)), 2*np.ones(len(year)), 2*np.ones(6), K, r1, n1, r0, n0, year)

/var/folders/tg/thybpd9j15j5gx8z__ml1jgm0000gn/T/ipykernel_8071/2513530126.py:30: RuntimeWarning: divide by zero encountered in log
  top = - (prop**2 / (2 * 1e6)) + sum(r1 * np.log(prop_p1)) + sum((n1 - r1) * np.log(1 - prop_p1))
/var/folders/tg/thybpd9j15j5gx8z__ml1jgm0000gn/T/ipykernel_8071/2513530126.py:31: RuntimeWarning: divide by zero encountered in log
  bottom = - (alpha**2 / (2 * 1e6)) + sum(r1 * np.log(p1)) + sum((n1 - r1) * np.log(1 - p1))
/var/folders/tg/thybpd9j15j5gx8z__ml1jgm0000gn/T/ipykernel_8071/2513530126.py:33: RuntimeWarning: invalid value encountered in double_scalars
  acc_prob = np.exp(top - bottom)
/var/folders/tg/thybpd9j15j5gx8z__ml1jgm0000gn/T/ipykernel_8071/2513530126.py:47: RuntimeWarning: divide by zero encountered in log
  top = - (prop**2 / (2 * 1e6)) + sum(r1 * np.log(prop_p1)) + sum((n1 - r1) * np.log(1 - prop_p1))
/var/folders/tg/thybpd9j15j5gx8z__ml1jgm0000gn/T/ipykernel_8071/2513530126.py:48: RuntimeWarning: divide by zero encountered in log
  bot

hehe_alpha
hehe_beta1
hehe_beta2
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
hehe_alpha
hehe_beta1
hehe_beta2
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b
mu
b

In [55]:
lol

array([[2, 2, 2,
        array([-2.70854737, -1.5359738 , -3.16677448, -3.96686594, -2.94927354,
       -3.28985967, -3.30781311, -3.32513663, -3.43532948, -2.96221649,
       -1.95149817, -1.57485402, -3.93718891, -1.42463649, -2.83826421,
       -2.2648325 , -1.60659663, -1.84247868, -2.40932589, -3.67328972,
       -2.65221538, -5.60426978, -3.04311625, -2.93630161, -2.90222685,
       -5.82239701, -2.05378163, -1.47527163, -2.54202546, -2.00174964,
       -1.39047373, -2.70880174, -2.99328832, -1.94177353, -0.62689158,
       -1.72274862, -2.51331084, -3.31141833, -1.62473424, -1.57049357,
       -3.1928381 , -2.09962854, -3.30402011, -2.81467725, -2.49102026,
       -2.2651764 , -2.71097146, -1.21501635, -2.11142424, -3.28943159,
       -2.29835841, -1.20428874, -1.70148634, -2.17281203, -1.9222382 ,
       -1.77612085, -1.65864842,  0.91740851, -1.26796867, -1.34960686,
       -1.75844871, -1.70039819, -1.99766277, -3.67986202, -2.88909447,
       -3.79514227, -2.29367158, -3.926

In [18]:
log_psi = 1 + 1 * year + 2 * (year**2 - 22) + np.ones(len(year))

In [20]:
mu = np.ones(len(year))

In [8]:
chain[0,0] = 1

In [26]:
10e6

10000000.0

In [10]:
chain[0,3] = ["a","b","c"]

In [11]:
chain

array([[1, 0, 0, list(['a', 'b', 'c']), 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=object)

In [12]:
chain[0,5] = np.array(["a","b","c"])

In [13]:
chain

array([[1, 0, 0, list(['a', 'b', 'c']), 0,
        array(['a', 'b', 'c'], dtype='<U1')],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=object)

In [15]:
chain = np.zeros((3, 6), dtype = object)
chain[0,0] = 1
chain[0,1] = 2
chain[0,2] = 3
chain[0,3] = 4
chain[0,4] = [1,2,3]
chain[0,5] = [1,2,3]

In [16]:
chain

array([[1, 2, 3, 4, list([1, 2, 3]), list([1, 2, 3])],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=object)

In [29]:
a = np.array([1,2,3])
b = np.array([1,1,1])

In [30]:
a*b

array([1, 2, 3])

In [23]:
a**2

array([1, 4, 9])

In [31]:
sum(a)

6

In [32]:
np.sum(a)

6